<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-BT3TDFN" name="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker" tests="6" failures="0" timestamp="2020-06-28T02:02:50 EET" time="3.776" errors="2">
  <testcase name="RegisteredUserCanLogout" time="1.960" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <skipped/>
  </testcase> <!-- RegisteredUserCanLogout -->
  <system-out/>
  <testcase name="RegisteredUserCanLogin" time="0.000" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <skipped/>
  </testcase> <!-- RegisteredUserCanLogin -->
  <system-out/>
  <testcase name="RegisteredUserCanLogout" time="1.650" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <skipped/>
  </testcase> <!-- RegisteredUserCanLogout -->
  <system-out/>
  <testcase name="RegisteredUserCanLogin" time="0.000" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <skipped/>
  </testcase> <!-- RegisteredUserCanLogin -->
  <system-out/>
  <testcase name="UserCanRegisterSuccssfully" time="0.084" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.TestBase2.getDriver(TestBase2.java:40)
at tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker.UserCanRegisterSuccssfully(UserRegistrationParalleltesting.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- UserCanRegisterSuccssfully -->
  <system-out/>
  <testcase name="UserCanRegisterSuccssfully" time="0.082" classname="tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.TestBase2.getDriver(TestBase2.java:40)
at tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker.UserCanRegisterSuccssfully(UserRegistrationParalleltesting.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- UserCanRegisterSuccssfully -->
  <system-out/>
</testsuite> <!-- tests.UserRegistrationParalleltesting$UserRegistrationTestWithJavaFaker -->
